In [2]:
from nmmo import Env
from ijcai2022nmmo import CompetitionConfig, scripted
import nmmo
from nmmo.lib import colors,material


######### create the env
env = Env(CompetitionConfig())

In [3]:
obs = env.reset()
print(obs.keys())
print(obs[1])

dict_keys([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128])
{'Entity': {'Continuous': array([[  1.,   1.,   0., ...,  10.,  10.,   0.],
       [  1., 105.,   0., ...,  10.,  10.,   0.],
       [  1., 106.,   0., ...,  10.,  10.,   0.],
       ...,
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.]], dtype=float32), 'Discrete': array([[  1,   5,  39, 197],
       [  1,  18,  37, 199],
       [  1,  18,  37, 203],
  

In [4]:
print(obs[1].keys())

dict_keys(['Entity', 'Tile'])


In [18]:
# ENTITY   ONLY consider the continuous state

obs[1]['Entity']['Continuous'].shape  # 100 * 13    总共可以观测到的agent的最大数量是 100（包括npc）， 特征类型是 13
# 0 - 是否包含信息    [0,1]
# 1 - entity-ID   ID>0 表示 players | ID<0 标识 NPC   [-128:-1](NPC) + [1,128] | 第一个是自己
# 2 - attracker ID ： 该entity 上一次被攻击 对应的 entity ID  NPC+[0,128]
# 3 - level： 该 entity 的level                            [1,max_level]   NPC max_level: 
# 4 - population : 该entity属于的队伍编号， 用于确定是队友还是敌人  NPC population<0  | team_id [0,15]
# 5 - Row_index: 所在的row   [16,144] (129个)
# 6 - column_index: 所处的column  [16，144] （129个）
# 7 - damage: 该entity已经受到的damage [0,infty]
# 8 - timealive： 该entity 已经活的时长 [0,1024]
# 9 - food： 该entity拥有的food  []
# 10 - water： 该entity拥有的water
# 11 - health： 该entity有的health     [10,]
# 12 - is_freezed: 该entity是否被冻结 [0,1]

print( obs[11]['Entity']['Continuous'][:,4] )
print( obs[1]['Entity']['Continuous'] )
#obs[1]['Tile']['Continuous'].shape # 225 * 4  15*15 * 4 
# 0 - N_entity: 该tile上的 entites数量
# 1 - type： tile type ： 0 - lava | 1 - water| 2 - grass | 3 - scrub | 4 - forest | 5 - stone
# 2 - row_index 
# 3 - column_index

#print(obs[1]['Tile']['Continuous'])


[1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
[[  1.   1.   0. ...  10.  10.   0.]
 [  1. 105.   0. ...  10.  10.   0.]
 [  1. 106.   0. ...  10.  10.   0.]
 ...
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]]


In [19]:
# action
1: {action.Attack:{
    action.Style: 0,
    action.Target: 3
    },
    action.Move: {
      action.Direction: 1
    }
  },
    

Style: 0,1,2
Target: entity_id
Move: 

SyntaxError: illegal target for annotation (2288507481.py, line 2)

In [91]:
from ijcai2022nmmo import CompetitionConfig, TeamBasedEnv
from nmmo.io import action
from ijcai2022nmmo import Team

env = TeamBasedEnv(CompetitionConfig())

class YourTeam(Team):
    def __init__(self, team_id: str, config=None, **kwargs): # team_id : 0-7
        super().__init__(team_id, config)
        self.team_id_int = int(team_id)
        self.player_id_set = [ self.team_id_int*7 + i+1  for i in range(8)]
        
    def act(self, observations):
        actions = {}
        for player_idx, obs in observations.items(): 
            actions[player_idx] = {}
        return actions
obs = env.reset()
#print(obs)
print(obs[0][0]['Tile']['Continuous'])
print(obs[0][0]['Tile']['Discrete'])

[[ 0.  0.  9. 11.]
 [ 0.  0.  9. 12.]
 [ 0.  0.  9. 13.]
 [ 0.  0.  9. 14.]
 [ 0.  0.  9. 15.]
 [ 0.  0.  9. 16.]
 [ 0.  0.  9. 17.]
 [ 0.  0.  9. 18.]
 [ 0.  0.  9. 19.]
 [ 0.  0.  9. 20.]
 [ 0.  0.  9. 21.]
 [ 0.  0.  9. 22.]
 [ 0.  0.  9. 23.]
 [ 0.  0.  9. 24.]
 [ 0.  0.  9. 25.]
 [ 0.  0. 10. 11.]
 [ 0.  0. 10. 12.]
 [ 0.  0. 10. 13.]
 [ 0.  0. 10. 14.]
 [ 0.  0. 10. 15.]
 [ 0.  0. 10. 16.]
 [ 0.  0. 10. 17.]
 [ 0.  0. 10. 18.]
 [ 0.  0. 10. 19.]
 [ 0.  0. 10. 20.]
 [ 0.  0. 10. 21.]
 [ 0.  0. 10. 22.]
 [ 0.  0. 10. 23.]
 [ 0.  0. 10. 24.]
 [ 0.  0. 10. 25.]
 [ 0.  0. 11. 11.]
 [ 0.  0. 11. 12.]
 [ 0.  0. 11. 13.]
 [ 0.  0. 11. 14.]
 [ 0.  0. 11. 15.]
 [ 0.  0. 11. 16.]
 [ 0.  0. 11. 17.]
 [ 0.  0. 11. 18.]
 [ 0.  0. 11. 19.]
 [ 0.  0. 11. 20.]
 [ 0.  0. 11. 21.]
 [ 0.  0. 11. 22.]
 [ 0.  0. 11. 23.]
 [ 0.  0. 11. 24.]
 [ 0.  0. 11. 25.]
 [ 0.  0. 12. 11.]
 [ 0.  0. 12. 12.]
 [ 0.  0. 12. 13.]
 [ 0.  0. 12. 14.]
 [ 0.  0. 12. 15.]
 [ 0.  0. 12. 16.]
 [ 0.  0. 12. 17.]
 [ 0.  0. 12

In [ ]:
'''Documented at neuralmmo.github.io'''

from pdb import set_trace as T

import nmmo

# Scripted models included with the baselines repository
from ijcai2022nmmo.scripted import baselines
from ijcai2022nmmo import CompetitionConfig

def simulate(env, config, render=False, horizon=float('inf')):
    '''Simulate an environment for a fixed horizon'''

    # Environment accepts a config object
    env = env(config())
    env.reset()

    t = 0
    while True:
        if render:
            env.render()

        # Scripted API computes actions
        obs, rewards, dones, infos = env.step({})

        # Later examples will use a fixed horizon
        t += 1
        if t >= horizon:
            break

    # Called at the end of simulation to obtain logs
    return env.terminal()


class Config(CompetitionConfig):
    '''Config objects subclass a nmmo.config.{Small, Medium, Large} template

    Can also specify config game systems to enable various features'''

    # Agents will be instantiated using templates included with the baselines
    # Meander: randomly wanders around
    # Forage: explicitly searches for food and water
    # Combat: forages and actively fights other agents
    AGENTS    = [baselines.Meander,baselines.Meander, baselines.Forage, baselines.Combat]*4

    #Set a unique path for demo maps
    PATH_MAPS = 'maps/demos'

    #Enable rendering
    RENDER = True

    #Force terrain generation -- avoids unexpected behavior from caching
    FORCE_MAP_GENERATION = True



if __name__ == '__main__':
    simulate(nmmo.Env, Config, render=True)


  5%|██▏                                         | 2/40 [00:00<00:02, 17.88it/s]

Generating 40 maps


100%|███████████████████████████████████████████| 40/40 [00:01<00:00, 20.49it/s]


2022-06-16 16:51:50+0800 [-] Log opened.
2022-06-16 16:51:50+0800 [-] Site starting on 8080
2022-06-16 16:51:50+0800 [-] Starting factory <twisted.web.server.Site object at 0x7f95758fa700>
2022-06-16 16:51:50+0800 [-] Wall Clock:  0.001 Uptime:  0.6 , Tick:  1
2022-06-16 16:51:51+0800 [-] Wall Clock:  0.227 Uptime:  1.2 , Tick:  2
2022-06-16 16:51:51+0800 [-] Wall Clock:  0.233 Uptime:  1.8 , Tick:  3
2022-06-16 16:51:52+0800 [-] Wall Clock:  0.263 Uptime:  2.4 , Tick:  4
2022-06-16 16:51:53+0800 [-] Wall Clock:  0.271 Uptime:  3.0 , Tick:  5
2022-06-16 16:51:53+0800 [-] Wall Clock:  0.270 Uptime:  3.6 , Tick:  6
2022-06-16 16:51:54+0800 [-] Wall Clock:  0.263 Uptime:  4.2 , Tick:  7
2022-06-16 16:51:54+0800 [-] Wall Clock:  0.260 Uptime:  4.8 , Tick:  8
2022-06-16 16:51:55+0800 [-] Wall Clock:  0.257 Uptime:  5.4 , Tick:  9
2022-06-16 16:51:56+0800 [-] Wall Clock:  0.267 Uptime:  6.0 , Tick:  10
2022-06-16 16:51:56+0800 [-] Wall Clock:  0.256 Uptime:  6.6 , Tick:  11
2022-06-16 16:51:

2022-06-16 16:52:24+0800 [-] Wall Clock:  0.154 Uptime:  34.2 , Tick:  57
2022-06-16 16:52:24+0800 [-] Server packet b'Recieved packet 26 from Server;80 80 '
2022-06-16 16:52:24+0800 [-] Is Connected? : True
2022-06-16 16:52:24+0800 [-] Wall Clock:  0.154 Uptime:  34.8 , Tick:  58
2022-06-16 16:52:25+0800 [-] Server packet b'Recieved packet 27 from Server;80 80 '
2022-06-16 16:52:25+0800 [-] Is Connected? : True
2022-06-16 16:52:25+0800 [-] Server packet b'Recieved packet 28 from Server;80 80 '
2022-06-16 16:52:25+0800 [-] Wall Clock:  0.151 Uptime:  35.4 , Tick:  59
2022-06-16 16:52:25+0800 [-] Is Connected? : True
2022-06-16 16:52:25+0800 [-] Server packet b'Recieved packet 29 from Server;80 80 '
2022-06-16 16:52:25+0800 [-] Wall Clock:  0.158 Uptime:  36.0 , Tick:  60
2022-06-16 16:52:26+0800 [-] Is Connected? : True
2022-06-16 16:52:26+0800 [-] Server packet b'Recieved packet 30 from Server;80 80 '
2022-06-16 16:52:26+0800 [-] Wall Clock:  0.147 Uptime:  36.6 , Tick:  61
2022-06-16

2022-06-16 16:52:48+0800 [-] Is Connected? : True
2022-06-16 16:52:48+0800 [-] Server packet b'Recieved packet 66 from Server;80 80 '
2022-06-16 16:52:48+0800 [-] Wall Clock:  0.141 Uptime:  58.2 , Tick:  97
2022-06-16 16:52:48+0800 [-] Is Connected? : True
2022-06-16 16:52:48+0800 [-] Wall Clock:  0.128 Uptime:  58.8 , Tick:  98
2022-06-16 16:52:48+0800 [-] Server packet b'Recieved packet 67 from Server;94 80 '
2022-06-16 16:52:49+0800 [-] Is Connected? : True
2022-06-16 16:52:49+0800 [-] Wall Clock:  0.134 Uptime:  59.4 , Tick:  99
2022-06-16 16:52:49+0800 [-] Server packet b'Recieved packet 68 from Server;95 80 '
2022-06-16 16:52:49+0800 [-] Is Connected? : True
2022-06-16 16:52:49+0800 [-] Wall Clock:  0.136 Uptime:  60.0 , Tick:  100
2022-06-16 16:52:50+0800 [-] Server packet b'Recieved packet 69 from Server;95 80 '
2022-06-16 16:52:50+0800 [-] Is Connected? : True
2022-06-16 16:52:50+0800 [-] Wall Clock:  0.136 Uptime:  60.6 , Tick:  101
2022-06-16 16:52:50+0800 [-] Server packet

2022-06-16 16:53:11+0800 [-] Server packet b'Recieved packet 105 from Server;82 80 '
2022-06-16 16:53:11+0800 [-] Wall Clock:  0.130 Uptime:  81.6 , Tick:  136
2022-06-16 16:53:12+0800 [-] Is Connected? : True
2022-06-16 16:53:12+0800 [-] Wall Clock:  0.122 Uptime:  82.2 , Tick:  137
2022-06-16 16:53:12+0800 [-] Server packet b'Recieved packet 106 from Server;82 80 '
2022-06-16 16:53:12+0800 [-] Is Connected? : True
2022-06-16 16:53:12+0800 [-] Wall Clock:  0.130 Uptime:  82.8 , Tick:  138
2022-06-16 16:53:12+0800 [-] Server packet b'Recieved packet 107 from Server;82 80 '
2022-06-16 16:53:13+0800 [-] Is Connected? : True
2022-06-16 16:53:13+0800 [-] Wall Clock:  0.123 Uptime:  83.4 , Tick:  139
2022-06-16 16:53:13+0800 [-] Server packet b'Recieved packet 108 from Server;82 80 '
2022-06-16 16:53:13+0800 [-] Is Connected? : True
2022-06-16 16:53:14+0800 [-] Wall Clock:  0.121 Uptime:  84.0 , Tick:  140
2022-06-16 16:53:14+0800 [-] Server packet b'Recieved packet 109 from Server;82 80 '


2022-06-16 16:53:34+0800 [-] Server packet b'Recieved packet 144 from Server;82 80 '
2022-06-16 16:53:35+0800 [-] Wall Clock:  0.116 Uptime:  105.0 , Tick:  175
2022-06-16 16:53:35+0800 [-] Is Connected? : True
2022-06-16 16:53:35+0800 [-] Wall Clock:  0.108 Uptime:  105.6 , Tick:  176
2022-06-16 16:53:35+0800 [-] Server packet b'Recieved packet 145 from Server;82 80 '
2022-06-16 16:53:36+0800 [-] Is Connected? : True
2022-06-16 16:53:36+0800 [-] Server packet b'Recieved packet 146 from Server;82 80 '
2022-06-16 16:53:36+0800 [-] Wall Clock:  0.117 Uptime:  106.2 , Tick:  177
2022-06-16 16:53:36+0800 [-] Is Connected? : True
2022-06-16 16:53:36+0800 [-] Wall Clock:  0.113 Uptime:  106.8 , Tick:  178
2022-06-16 16:53:36+0800 [-] Server packet b'Recieved packet 147 from Server;82 80 '
2022-06-16 16:53:37+0800 [-] Is Connected? : True
2022-06-16 16:53:37+0800 [-] Server packet b'Recieved packet 148 from Server;82 80 '
2022-06-16 16:53:37+0800 [-] Wall Clock:  0.114 Uptime:  107.4 , Tick: 

2022-06-16 16:53:58+0800 [-] Wall Clock:  0.112 Uptime:  128.4 , Tick:  214
2022-06-16 16:53:58+0800 [-] Server packet b'Recieved packet 183 from Server;82 80 '
2022-06-16 16:53:58+0800 [-] Is Connected? : True
2022-06-16 16:53:59+0800 [-] Wall Clock:  0.114 Uptime:  129.0 , Tick:  215
2022-06-16 16:53:59+0800 [-] Server packet b'Recieved packet 184 from Server;82 80 '
2022-06-16 16:53:59+0800 [-] Is Connected? : True
2022-06-16 16:53:59+0800 [-] Server packet b'Recieved packet 185 from Server;82 80 '
2022-06-16 16:53:59+0800 [-] Wall Clock:  0.113 Uptime:  129.6 , Tick:  216
2022-06-16 16:54:00+0800 [-] Is Connected? : True
2022-06-16 16:54:00+0800 [-] Server packet b'Recieved packet 186 from Server;82 80 '
2022-06-16 16:54:00+0800 [-] Wall Clock:  0.116 Uptime:  130.2 , Tick:  217
2022-06-16 16:54:00+0800 [-] Is Connected? : True
2022-06-16 16:54:00+0800 [-] Wall Clock:  0.106 Uptime:  130.8 , Tick:  218
2022-06-16 16:54:00+0800 [-] Server packet b'Recieved packet 187 from Server;82 

2022-06-16 16:54:21+0800 [-] Is Connected? : True
2022-06-16 16:54:21+0800 [-] Server packet b'Recieved packet 222 from Server;27 80 '
2022-06-16 16:54:21+0800 [-] Wall Clock:  0.118 Uptime:  151.8 , Tick:  253
2022-06-16 16:54:22+0800 [-] Is Connected? : True
2022-06-16 16:54:22+0800 [-] Server packet b'Recieved packet 223 from Server;27 80 '
2022-06-16 16:54:22+0800 [-] Wall Clock:  0.115 Uptime:  152.4 , Tick:  254
2022-06-16 16:54:23+0800 [-] Is Connected? : True
2022-06-16 16:54:23+0800 [-] Server packet b'Recieved packet 224 from Server;27 80 '
2022-06-16 16:54:23+0800 [-] Wall Clock:  0.113 Uptime:  153.0 , Tick:  255
2022-06-16 16:54:23+0800 [-] Is Connected? : True
2022-06-16 16:54:23+0800 [-] Server packet b'Recieved packet 225 from Server;27 80 '
2022-06-16 16:54:23+0800 [-] Wall Clock:  0.109 Uptime:  153.6 , Tick:  256
2022-06-16 16:54:24+0800 [-] Is Connected? : True
2022-06-16 16:54:24+0800 [-] Wall Clock:  0.102 Uptime:  154.2 , Tick:  257
2022-06-16 16:54:24+0800 [-] S

2022-06-16 16:54:45+0800 [-] Is Connected? : True
2022-06-16 16:54:45+0800 [-] Server packet b'Recieved packet 261 from Server;77 80 '
2022-06-16 16:54:45+0800 [-] Wall Clock:  0.110 Uptime:  175.2 , Tick:  292
2022-06-16 16:54:45+0800 [-] Is Connected? : True
2022-06-16 16:54:45+0800 [-] Wall Clock:  0.103 Uptime:  175.8 , Tick:  293
2022-06-16 16:54:46+0800 [-] Server packet b'Recieved packet 262 from Server;77 80 '
2022-06-16 16:54:46+0800 [-] Is Connected? : True
2022-06-16 16:54:46+0800 [-] Wall Clock:  0.103 Uptime:  176.4 , Tick:  294
2022-06-16 16:54:46+0800 [-] Server packet b'Recieved packet 263 from Server;77 80 '
2022-06-16 16:54:47+0800 [-] Is Connected? : True
2022-06-16 16:54:47+0800 [-] Server packet b'Recieved packet 264 from Server;80 80 '
2022-06-16 16:54:47+0800 [-] Wall Clock:  0.108 Uptime:  177.0 , Tick:  295
2022-06-16 16:54:47+0800 [-] Is Connected? : True
2022-06-16 16:54:47+0800 [-] Wall Clock:  0.097 Uptime:  177.6 , Tick:  296
2022-06-16 16:54:47+0800 [-] S

2022-06-16 16:55:08+0800 [-] Is Connected? : True
2022-06-16 16:55:08+0800 [-] Wall Clock:  0.099 Uptime:  198.6 , Tick:  331
2022-06-16 16:55:08+0800 [-] Server packet b'Recieved packet 300 from Server;51 80 '
2022-06-16 16:55:09+0800 [-] Is Connected? : True
2022-06-16 16:55:09+0800 [-] Server packet b'Recieved packet 301 from Server;51 80 '
2022-06-16 16:55:09+0800 [-] Wall Clock:  0.103 Uptime:  199.2 , Tick:  332
2022-06-16 16:55:09+0800 [-] Is Connected? : True
2022-06-16 16:55:09+0800 [-] Server packet b'Recieved packet 302 from Server;51 80 '
2022-06-16 16:55:10+0800 [-] Wall Clock:  0.108 Uptime:  199.8 , Tick:  333
2022-06-16 16:55:10+0800 [-] Is Connected? : True
2022-06-16 16:55:10+0800 [-] Server packet b'Recieved packet 303 from Server;51 80 '
2022-06-16 16:55:10+0800 [-] Wall Clock:  0.104 Uptime:  200.4 , Tick:  334
2022-06-16 16:55:11+0800 [-] Is Connected? : True
2022-06-16 16:55:11+0800 [-] Wall Clock:  0.096 Uptime:  201.0 , Tick:  335
2022-06-16 16:55:11+0800 [-] S

2022-06-16 16:55:32+0800 [-] Is Connected? : True
2022-06-16 16:55:32+0800 [-] Wall Clock:  0.100 Uptime:  222.0 , Tick:  370
2022-06-16 16:55:32+0800 [-] Server packet b'Recieved packet 339 from Server;52 80 '
2022-06-16 16:55:32+0800 [-] Is Connected? : True
2022-06-16 16:55:32+0800 [-] Server packet b'Recieved packet 340 from Server;52 80 '
2022-06-16 16:55:32+0800 [-] Wall Clock:  0.096 Uptime:  222.6 , Tick:  371
2022-06-16 16:55:33+0800 [-] Is Connected? : True
2022-06-16 16:55:33+0800 [-] Wall Clock:  0.100 Uptime:  223.2 , Tick:  372
2022-06-16 16:55:33+0800 [-] Server packet b'Recieved packet 341 from Server;52 80 '
2022-06-16 16:55:33+0800 [-] Is Connected? : True
2022-06-16 16:55:34+0800 [-] Wall Clock:  0.098 Uptime:  223.8 , Tick:  373
2022-06-16 16:55:34+0800 [-] Server packet b'Recieved packet 342 from Server;52 80 '
2022-06-16 16:55:34+0800 [-] Is Connected? : True
2022-06-16 16:55:34+0800 [-] Wall Clock:  0.095 Uptime:  224.4 , Tick:  374
2022-06-16 16:55:34+0800 [-] S

2022-06-16 16:55:55+0800 [-] Is Connected? : True
2022-06-16 16:55:55+0800 [-] Server packet b'Recieved packet 378 from Server;119 80 '
2022-06-16 16:55:55+0800 [-] Wall Clock:  0.100 Uptime:  245.4 , Tick:  409
2022-06-16 16:55:56+0800 [-] Is Connected? : True
2022-06-16 16:55:56+0800 [-] Server packet b'Recieved packet 379 from Server;119 80 '
2022-06-16 16:55:56+0800 [-] Wall Clock:  0.104 Uptime:  246.0 , Tick:  410
2022-06-16 16:55:56+0800 [-] Is Connected? : True
2022-06-16 16:55:56+0800 [-] Wall Clock:  0.094 Uptime:  246.6 , Tick:  411
2022-06-16 16:55:56+0800 [-] Server packet b'Recieved packet 380 from Server;119 80 '
2022-06-16 16:55:57+0800 [-] Is Connected? : True
2022-06-16 16:55:57+0800 [-] Server packet b'Recieved packet 381 from Server;119 80 '
2022-06-16 16:55:57+0800 [-] Wall Clock:  0.099 Uptime:  247.2 , Tick:  412
2022-06-16 16:55:58+0800 [-] Is Connected? : True
2022-06-16 16:55:58+0800 [-] Wall Clock:  0.088 Uptime:  247.8 , Tick:  413
2022-06-16 16:55:58+0800 [

2022-06-16 16:56:19+0800 [-] Is Connected? : True
2022-06-16 16:56:19+0800 [-] Wall Clock:  0.097 Uptime:  268.8 , Tick:  448
2022-06-16 16:56:19+0800 [-] Server packet b'Recieved packet 417 from Server;119 80 '
2022-06-16 16:56:19+0800 [-] Is Connected? : True
2022-06-16 16:56:19+0800 [-] Server packet b'Recieved packet 418 from Server;119 80 '
2022-06-16 16:56:19+0800 [-] Wall Clock:  0.099 Uptime:  269.4 , Tick:  449
2022-06-16 16:56:20+0800 [-] Is Connected? : True
2022-06-16 16:56:20+0800 [-] Server packet b'Recieved packet 419 from Server;119 80 '
2022-06-16 16:56:20+0800 [-] Wall Clock:  0.104 Uptime:  270.0 , Tick:  450
2022-06-16 16:56:20+0800 [-] Is Connected? : True
2022-06-16 16:56:20+0800 [-] Wall Clock:  0.097 Uptime:  270.6 , Tick:  451
2022-06-16 16:56:21+0800 [-] Server packet b'Recieved packet 420 from Server;119 80 '
2022-06-16 16:56:21+0800 [-] Is Connected? : True
2022-06-16 16:56:21+0800 [-] Server packet b'Recieved packet 421 from Server;119 80 '
2022-06-16 16:56

2022-06-16 16:56:42+0800 [-] Is Connected? : True
2022-06-16 16:56:42+0800 [-] Server packet b'Recieved packet 456 from Server;30 80 '
2022-06-16 16:56:42+0800 [-] Wall Clock:  0.094 Uptime:  292.2 , Tick:  487
2022-06-16 16:56:43+0800 [-] Is Connected? : True
2022-06-16 16:56:43+0800 [-] Server packet b'Recieved packet 457 from Server;30 80 '
2022-06-16 16:56:43+0800 [-] Wall Clock:  0.091 Uptime:  292.8 , Tick:  488
2022-06-16 16:56:43+0800 [-] Is Connected? : True
2022-06-16 16:56:43+0800 [-] Wall Clock:  0.088 Uptime:  293.4 , Tick:  489
2022-06-16 16:56:43+0800 [-] Server packet b'Recieved packet 458 from Server;30 80 '
2022-06-16 16:56:44+0800 [-] Is Connected? : True
2022-06-16 16:56:44+0800 [-] Wall Clock:  0.089 Uptime:  294.0 , Tick:  490
2022-06-16 16:56:44+0800 [-] Server packet b'Recieved packet 459 from Server;30 80 '
2022-06-16 16:56:44+0800 [-] Is Connected? : True
2022-06-16 16:56:44+0800 [-] Wall Clock:  0.091 Uptime:  294.6 , Tick:  491
2022-06-16 16:56:45+0800 [-] S

2022-06-16 16:57:05+0800 [-] Is Connected? : True
2022-06-16 16:57:06+0800 [-] Wall Clock:  0.085 Uptime:  315.6 , Tick:  526
2022-06-16 16:57:06+0800 [-] Server packet b'Recieved packet 495 from Server;30 80 '
2022-06-16 16:57:06+0800 [-] Is Connected? : True
2022-06-16 16:57:06+0800 [-] Wall Clock:  0.083 Uptime:  316.2 , Tick:  527
2022-06-16 16:57:06+0800 [-] Server packet b'Recieved packet 496 from Server;30 80 '
2022-06-16 16:57:07+0800 [-] Is Connected? : True
2022-06-16 16:57:07+0800 [-] Wall Clock:  0.090 Uptime:  316.8 , Tick:  528
2022-06-16 16:57:07+0800 [-] Server packet b'Recieved packet 497 from Server;52 80 '
2022-06-16 16:57:07+0800 [-] Is Connected? : True
2022-06-16 16:57:07+0800 [-] Server packet b'Recieved packet 498 from Server;52 80 '
2022-06-16 16:57:07+0800 [-] Wall Clock:  0.084 Uptime:  317.4 , Tick:  529
2022-06-16 16:57:08+0800 [-] Is Connected? : True
2022-06-16 16:57:08+0800 [-] Server packet b'Recieved packet 499 from Server;52 80 '
2022-06-16 16:57:08+0

2022-06-16 16:57:29+0800 [-] Is Connected? : True
2022-06-16 16:57:29+0800 [-] Wall Clock:  0.086 Uptime:  339.0 , Tick:  565
2022-06-16 16:57:29+0800 [-] Server packet b'Recieved packet 534 from Server;60 80 '
2022-06-16 16:57:29+0800 [-] Is Connected? : True
2022-06-16 16:57:30+0800 [-] Wall Clock:  0.076 Uptime:  339.6 , Tick:  566
2022-06-16 16:57:30+0800 [-] Server packet b'Recieved packet 535 from Server;60 80 '
2022-06-16 16:57:30+0800 [-] Is Connected? : True
2022-06-16 16:57:30+0800 [-] Server packet b'Recieved packet 536 from Server;60 80 '
2022-06-16 16:57:30+0800 [-] Wall Clock:  0.085 Uptime:  340.2 , Tick:  567
2022-06-16 16:57:31+0800 [-] Is Connected? : True
2022-06-16 16:57:31+0800 [-] Server packet b'Recieved packet 537 from Server;60 80 '
2022-06-16 16:57:31+0800 [-] Wall Clock:  0.085 Uptime:  340.8 , Tick:  568
2022-06-16 16:57:31+0800 [-] Is Connected? : True
2022-06-16 16:57:31+0800 [-] Wall Clock:  0.085 Uptime:  341.4 , Tick:  569
2022-06-16 16:57:31+0800 [-] S

2022-06-16 16:57:52+0800 [-] Is Connected? : True
2022-06-16 16:57:52+0800 [-] Wall Clock:  0.076 Uptime:  362.4 , Tick:  604
2022-06-16 16:57:52+0800 [-] Server packet b'Recieved packet 573 from Server;60 80 '
2022-06-16 16:57:53+0800 [-] Is Connected? : True
2022-06-16 16:57:53+0800 [-] Wall Clock:  0.083 Uptime:  363.0 , Tick:  605
2022-06-16 16:57:53+0800 [-] Server packet b'Recieved packet 574 from Server;60 80 '
2022-06-16 16:57:54+0800 [-] Is Connected? : True
2022-06-16 16:57:54+0800 [-] Server packet b'Recieved packet 575 from Server;60 80 '
2022-06-16 16:57:54+0800 [-] Wall Clock:  0.085 Uptime:  363.6 , Tick:  606
2022-06-16 16:57:54+0800 [-] Is Connected? : True
2022-06-16 16:57:54+0800 [-] Server packet b'Recieved packet 576 from Server;60 80 '
2022-06-16 16:57:54+0800 [-] Wall Clock:  0.087 Uptime:  364.2 , Tick:  607
2022-06-16 16:57:55+0800 [-] Is Connected? : True
2022-06-16 16:57:55+0800 [-] Wall Clock:  0.073 Uptime:  364.8 , Tick:  608
2022-06-16 16:57:55+0800 [-] S

2022-06-16 16:58:19+0800 [-] Wall Clock:  0.073 Uptime:  389.4 , Tick:  649


In [20]:
from ijcai2022nmmo import CompetitionConfig, scripted, TeamBasedEnv
import nmmo
import numpy as np
import copy


class TeamBasedEnv(object):
    players: Dict[int, entity.Player] = {}
    player_team_map: Dict[int, int] = {}
    team_players_map: Dict[int, List[int]] = {}

    def __init__(self, config: nmmo.config.Config) -> None:
        self._env = nmmo.Env(config)

    def __getattr__(self, __name: str) -> Any:
        if __name not in self.__dict__:
            return getattr(self._env, __name)

    def reset(self) -> Dict[int, Dict[int, dict]]: # team_id | agent_id | 'Entity','Tile'
        self.players.clear()
        self.player_team_map.clear()
        self.team_players_map.clear()

        observations = self._env.reset(None, True)
        for player in self._env.realm.players.entities.values():
            player: entity.Player
            self.players[player.entID] = player
            self.player_team_map[player.entID] = player.pop  # 根据 palyer_id 得到 player population
            if player.pop not in self.team_players_map:
                self.team_players_map[player.pop] = []
            self.team_players_map[player.pop].append(player.entID) # 根据 player population 得到对应的 agent id
        
        # 根据 player id 获得对应的 entity.Player: self.players[player_id] -> entity.PLayer
        # 根据player id 获得 population：  self.player_team_map[player_id] -> population
        # 根据population 获得 对应的所有play id list: self.team_players_map[population] -> [player_id] 
        return self._split_by_team(observations)

    def step(
        self,
        actions_by_team: Dict[int, Dict[int, dict]],
    ) -> Tuple[Dict[int, Dict[int, dict]], Dict[int, Dict[int, int]], Dict[
            int, Dict[int, bool]], Dict[int, Dict[int, dict]]]: # obs, reward, done, info
        # merge actions
        actions = {}
        for team_idx, team_actions in actions_by_team.items():  # team_idx = population id [0,15]
            player_ids = self.team_players_map[team_idx] # 该population 对应的 player ids
            for i, action in team_actions.items():  # i -> [0,7]
                # avoid invalid player id
                if i >= 0 and i < len(player_ids):
                    actions[player_ids[i]] = action

        observations, rewards, dones, infos = self._env.step(actions)

        # delete the observations of the done players
        for player_id, done in dones.items():
            if done and player_id in observations:
                del observations[player_id]  # done之后的 agent是没有observation的

        return (
            self._split_by_team(observations),
            self._split_by_team(rewards),
            self._split_by_team(dones),
            self._split_by_team(infos),
        )

    def metrices_by_team(self) -> Dict[int, Dict[int, Metrics]]:
        metrices: Dict[int, Metrics] = {}
        for player in self.players.values():
            metrices[player.entID] = Metrics.collect(self, player)
        return self._split_by_team(metrices)

    def stat_by_team(self) -> Dict[int, Stat]:
        stat_by_team = {}
        for team_idx, metrices in self.metrices_by_team().items():
            stat_by_team[team_idx] = Stat.from_metrices(metrices.values())
        return stat_by_team

    def _split_by_team(self, xs: Dict[int, Any]) -> Dict[int, Dict[int, Any]]:
        xs_by_team = {}
        for player_id, x in xs.items():
            team_idx = self.player_team_map[player_id]
            if team_idx not in xs_by_team:
                xs_by_team[team_idx] = {}
            xs_by_team[team_idx][self.team_players_map[team_idx].index(
                player_id)] = x
        return xs_by_team


NameError: name 'Dict' is not defined

In [21]:
import matplotlib.pyplot as plt

plt.figure(0)

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

In [ ]:
        obs = self.obs_normalization(agent_layers,agent_vectors,opponents,npcs,terrain)

        obs_layers = np.concatenate( (agent_layers,opponents,npcs,terrain),axis=-1 )

In [7]:
import copy
import numpy as np
a = np.random.uniform(size=(2,2,2))
print(a)
a = np.clip(a,0.1,0.5)
print(a)

[[[0.72027939 0.07392239]
  [0.85496848 0.12573567]]

 [[0.53463894 0.28459822]
  [0.84657292 0.76866796]]]
[[[0.5        0.1       ]
  [0.5        0.12573567]]

 [[0.5        0.28459822]
  [0.5        0.5       ]]]
